### ISSUE TITLE
Auto play

### ISSUE THREAD

**Issue by hbredin** [ghostsphinx/camomile-web-label#1]
The question asked is: "is the person speaking and visible at any time of the video?" and not just "is the person speaking and visible at the beginning of the video?".

Therefore, can you make sure the video starts playing as soon as it is loaded?
This will make sure the annotator does not waste time clicking on the "Play" button (which he will certainly have to press anyway).

**Comment by ghostsphinx** [comment]
The video autoplays and loops.
