### ISSUE TITLE
Logging in for each image?

### ISSUE THREAD

**Issue by hbredin** [ghostsphinx/camomile-web-label#6]
Looks like the part of the server that periodically updates the face images does a lot of logging in.

Can you update it so that it logs in only once at the beginning of each refresh, rather than once for each image?

**Comment by ghostsphinx** [comment]
My bad, I wanted to be sure it will load every image. I remove the log_in for every image, but I still can't log_out at the end, loading takes too much time and some of the images are not loaded correctly.

**Comment by ghostsphinx** [comment]
I think this issue is resolved now.
