### ISSUE TITLE
Tooltip incorrect

### ISSUE THREAD

**Issue by hbredin** [ghostsphinx/camomile-web-label#7]
![screenshot](https://cloud.githubusercontent.com/assets/1080837/16901504/46dc9b94-4c46-11e6-9aaa-668db423f378.jpg)

L'imagette est bien celle de michel_leuthy
Mais le "tooltip" affiché (ici : stephane_mari) n'est pas le bon.

Une fois corrigé, il faudra aussi vérifier que c'est bien le bon "person_name" qui est envoyé.

**Comment by ghostsphinx** [comment]
I think this is resolved, tests on Firefox and Chrome are positive for me.
